language: node_js
node_js:
- '10'
stages:
- name: npm release
  if: tag IS present
jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: npm run build
    deploy:
      provider: npm
      email: yuriy.bogomolov@gmail.com
      api_key:
        secure: qRGnKupEfkYgYmS6bFwFKCv/0ctHez3xj5xKkYFBeIky8OcNE6RSFfZPXH5ZAeaLiyLC7V1VfU7JbKbYWn+wqKly/NromGyg1na96yDxlMxanVNeNca/C2QFc6lScNqu/PE5NN1ot3lclDtJ/V8R5TAa8CKYHj0Wp55MHLonxZ5/Fl0gadc3GZrTJzg3N8fLTRPylJv24RrvR+28Hnai3tO6zOAqNmAAKIl1MjjAXN59zHmqVhIP4wvdaRQaWvt7IqcFBI9AzdqXHlvUEDekKPwBvd6vFgTbybhl3Vm9y2QX27yEbR1O7X+6mxlkikMSbYUaVLIpRDikDFFWmSmhe6gCxX/ZVc7B9M7Dy5W6EfHc/lNEzL5mslD6QaF4xD8Bmvw48ZxSk7Q5Heh4qJytU3TjfY/5iNN/prZioiIizJPz/E0nVHSv3dv2jBeM6h1FY7+H+QozlLADNK9HwXli0hwtmjxu7kFoHjR/kL645eekw1sp8auBp+pdECV7dQn5CDln6nES4qmPWclwJO7vWzp+WJm7qHUVAFloGn1bwQ9jdw+eE/UJNsLeDaRL9fm7tEqwH2I7SHC7OqhSBZ3QnAGnq++en0hdOpf//t7TkmhcNv9Bme3k1juA/fMuRCWSLinKEav5B6/B9kVEAtmuy303b4WLCfJs3kz52bX9ndI=
      skip_cleanup: true
      on:
        tags: true
deploy:
  api_key:
    secure: DVsWTTDakkZYuqmgNqoGWl7ybrR4lq4z1ALuhqOBwgZbw++AQ51iQtNNGkspJT0avvCOkykqvRoBlhMPQAfWE7mQaaQXBGi4sHXwdr9Ud+ggrD8qjTGFqPz8Qx6C2bDq/JneTtwozuxqALykvSI1zqMrEx0rR+3fCns5AbgBYoR0Tbw6MnyS0LdbDy5z0wVAmtEGXZ9fQCDD9Kwq9klgdWxo9CPSA1dm+ZP07jKYsKNXFev2Z+ElJRpbXaTk45es3ykBe2IcbCUf7gjbPJQ44zrZ+H5qKbcjuJI23uJCK5it9SmwNHSPNu1aWM/jfB9QlrMLR9o5JNta7/uXktmEyGWRXBZ+L6m0b4v+XH7Uqk5vqhRMRMYtOnz7SdobMrSpSzvLVXCh1Qxke8oQ2F0woDIC8D8ScZtLDcwqY9GHbizgWOy3WuKyZN1kohmfjS/PdZnwkmgSaziHq7YhKkqNS/aj2utdmOo903LjKaQDigfIGNwxVjXqv2IJuJ9/Qqg9RbaGNFEvtkY0/mTPyJrBtSf9tGjMqADqE4Gpm8XLcftHbtMm5dLc/8wX2Eq8bB+fU5qZ2XlqUz1racw7lYE9oZPOA8xDWZOTXzTRSzBjlan7hoGuJaPm/ABGkxD1aKu4NyGuuDly+4UWHRbbM8jcy+qATCwLgKh0jKyh3dG9lYA=
